### ISSUE TITLE
OkHttpClient.Builder refers to the missing type Interceptor

### ISSUE THREAD

**Issue by kernelogic** [binance-exchange/binance-java-api#1]
Getting an error when try to use this:

Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The method interceptors() from the type OkHttpClient.Builder refers to the missing type Interceptor
	The method addInterceptor(Interceptor) from the type OkHttpClient.Builder refers to the missing type Interceptor

	at com.binance.api.client.impl.BinanceApiServiceGenerator.createService(BinanceApiServiceGenerator.java:38)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.<init>(BinanceApiRestClientImpl.java:37)
	at com.binance.api.client.BinanceApiClientFactory.newRestClient(BinanceApiClientFactory.java:58)
	at binance.BinanceScapper.main(BinanceScapper.java:13)

**Comment by joaopsilva** [comment]
Hi @kernelogic, could you please provide the full stacktrace and your project's pom file?

**Comment by kernelogic** [comment]
![wx20171103-213618](https://user-images.githubusercontent.com/3711825/32401925-123b407a-c0df-11e7-9513-f0efe173257b.png)
It might be an issue with my Eclipse. I didn't do anything, just download your repository and import into Eclipse. Immediately see this error.

**Comment by kernelogic** [comment]
Oh ya never mind. It turned out this particular class was corrupted during maven download. I cleaned up .m2 folder and it's fine now.
