### ISSUE TITLE
java.io.EOFException: null when using Aggregate Trade Streams

### ISSUE THREAD

**Issue by brintal** [binance-exchange/binance-java-api#101]
I'm using the BinanceApiWebSocketClient to create a local cache for the AggTrade Stream like in this example:
https://github.com/binance-exchange/binance-java-api/blob/master/src/test/java/com/binance/api/examples/AggTradesCacheExample.java

Since yesterday I'm running into a "java.io.EOFException: null". My initial thought was that I was getting disconnected by the server because I was connected for too long, but it also happened shortly after a complete server restart.
What might be the problem here?

Stacktrace:
`java.io.EOFException: null
	at okio.RealBufferedSource.require(RealBufferedSource.java:60)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by okieven** [comment]
I'm facing exactly the same issue with candlestick streams. It seems to me that it appears totally random.

**Comment by skergetd** [comment]
Did anyone solve this? For me its sam with kline stream...

**Comment by GabBurnett** [comment]
Getting this exact same stacktrace when using BinanceApiWebSocketClient. (Java 8, Debian 8)

**Comment by brintal** [comment]
I ended up ignoring the error and implementing a routine which periodically checks if my streams are still open and reconnects if necessary.
I'm still getting the error but it doesn't really affect my trading anymore.

**Comment by GabBurnett** [comment]
I just looked through my logs and this occurred exactly 24 hours after the web sockets were initiated. Closing and reopening the connection every 23ish hours might solve this problem.

**Comment by skergetd** [comment]
Ok, my problem was, that my client was pinging binance api and this is obviously not supported. After I disabled ping, its working fine for me.

**Comment by joaopsilva** [comment]
Closing this one, the library has since been improved, to automatically deal with the client being disconnected. In any case, you should your own fail-safe methods to restart the connection whenever it fails.
