### ISSUE TITLE
JsonParseException happening irregularly

### ISSUE THREAD

**Issue by tomastoth** [binance-exchange/binance-java-api#121]
Hey guys, multiple days in row in random hours I keep getting this error:
`Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: okhttp3.ResponseBody$BomAwareReader@56f0cc85; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:450)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1823)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:708)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:358)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1558)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1183)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at com.binance.api.client.impl.BinanceApiServiceGenerator.getBinanceApiError(BinanceApiServiceGenerator.java:69)
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:56)
	... 2 more
`
When calling any api method. It keeps happening for like half an hour up to one hour and then stops which basically makes the api unusable overall. Any idea how to make it work?

**Comment by joaopsilva** [comment]
My guess is either the server API is down during those periods, or the connection was dropped. I have since merged a few changes that help with connectivity, please update your repo and see if it helps.
