### ISSUE TITLE
Error when initialising BinanceApiRestClient

### ISSUE THREAD

**Issue by Benjamous** [binance-exchange/binance-java-api#131]
I just tried :

BinanceApiClientFactory factory = BinanceApiClientFactory.newInstance("XXX", "XXX");
		BinanceApiRestClient client = factory.newRestClient();
		client.ping();
		long serverTime = client.getServerTime();
		System.out.println(serverTime);

And this occur: 

Exception in thread "main" java.lang.NoClassDefFoundError: retrofit2/Converter$Factory
	at com.binance.api.client.impl.BinanceApiRestClientImpl.<init>(BinanceApiRestClientImpl.java:42)
	at com.binance.api.client.BinanceApiClientFactory.newRestClient(BinanceApiClientFactory.java:58)
	at Main.main(Main.java:8)
Caused by: java.lang.ClassNotFoundException: retrofit2.Converter$Factory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more

any ideas how to fix it ?

**Comment by pantoea** [comment]
java.lang.NoClassDefFoundError: means, that the class which you are trying to run was not found in the classpath. Solution: you need to add the class or .jar file which contains this class into the java classpath.

**Comment by Benjamous** [comment]
Thanks man 👍 I thought that I had a problem with the api but it needed other libs that's what I didn't get thanks so for having spent some time for me 😄
