### ISSUE TITLE
Signature for this request is not valid.

### ISSUE THREAD

**Issue by ngocnam1202** [binance-exchange/binance-java-api#132]
Hi,

I want to test creating new order by comment line 31-53 in file OrdersExample, but the error occur.

Exception in thread "main" com.binance.api.client.exception.BinanceApiException: Signature for this request is not valid.
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:57)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.newOrder(BinanceApiRestClientImpl.java:133)
	at com.binance.api.examples.OrdersExample.main(OrdersExample.java:56)

PS: my API_KEY and SECRET are correct.
Please help.
Thank you so much.

**Comment by joaopsilva** [comment]
I'm unable to reproduce this problem, please check that the key and secret are correct, and that you have enable your keys to be used for trading.
