### ISSUE TITLE
exception when to get orderbook

### ISSUE THREAD

**Issue by ferankliu** [binance-exchange/binance-java-api#14]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: okhttp3.ResponseBody$BomAwareReader@4cb23097; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:450)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1823)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:708)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:358)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1558)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1183)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at com.binance.api.client.impl.BinanceApiServiceGenerator.getBinanceApiError(BinanceApiServiceGenerator.java:69)
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:56)
	... 5 more

**Comment by joaopsilva** [comment]
Hi @ferankliu , could you please give me more details, and provide the full stacktrace, and the code which you are using that has caused this error? Thanks.

**Comment by joaopsilva** [comment]
I'm unable to reproduce this problem, please re-open the issue with more details, if it happens again. Thanks.
