### ISSUE TITLE
SocketTimeoutException while getting trades

### ISSUE THREAD

**Issue by fconsani** [binance-exchange/binance-java-api#142]
Hello,

I am having some Exception randomly thown when i try to get Trades from client.
Here is the Exception : 

`Exception in thread "Timer-0" com.binance.api.client.exception.BinanceApiException: java.net.SocketTimeoutException: Read timed out
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:60)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getMyTrades(BinanceApiRestClientImpl.java:183)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getMyTrades(BinanceApiRestClientImpl.java:193)
	at com.mycompany.cryptobot.strategie.thread.Advanced_task.run(Advanced_task.java:63)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.binance.api.client.security.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:52)
	... 5 more`

I am getting this Error on a thread launched every 5s with an already initiated clients, and getting trades from this client.

Simply launching this on the thread : 

`this.openOrders` = client.getOpenOrders(new OrderRequest(this.pair));
this.myTrades = `client.getMyTrades(pair);`

Is it something related to the face that i am passing an already initiated client ? Do I have to initiate it each time the thread is ran ?

**Comment by big-andy-coates** [comment]
Can often mean the server dropped the connection. (Which it does periodically to clean out old clients). You should handle this by recreating the connection, e.g. by implementing `BinanceApiCallback.onFailure` to recreate your ws.

**Comment by joaopsilva** [comment]
This has since been improved, please update your repo.
