### ISSUE TITLE
Buy Order (Market) Occasionally Fails Due to Exception in thread "OKHttp Dispatcher" ClassNotFoundException

### ISSUE THREAD

**Issue by bonobo1984** [binance-exchange/binance-java-api#151]
Would appreciate any input or advice on what could be causing this issue.  Thanks

Here is the line of code that is executed:
client.newOrder(marketBuy(ticker.toUpperCase() +"USDT",amountToBuy.toPlainString()));	

Here is the stack trace for the exception:
Exception in thread "OkHttp Dispatcher" java.lang.NoClassDefFoundError: com/binance/api/client/domain/account/NewOrder
        at com.myApp.lambda$0(App.java:94)
        at com.binance.api.client.impl.BinanceApiWebSocketListener.onMessage(BinanceApiWebSocketListener.java:45)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.binance.api.client.domain.account.NewOrder
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more

**Comment by big-andy-coates** [comment]
Probably related to the #152 issue you also created. Get to the bottom of one and you'll get to the bottom of the other.

**Comment by joaopsilva** [comment]
Closing as this has to do with another dependency of the project.
