### ISSUE TITLE
Web Socket Connection Occasionally Closing Due to Exception in Thread "OK Dispatcher" ConnectionShutdownException

### ISSUE THREAD

**Issue by bonobo1984** [binance-exchange/binance-java-api#152]
I have a running application with an web socket connection returning a stream of candlestickevents, however, my connection is occasionally being closed due to the following exception:
Exception in thread "OkHttp Dispatcher" java.lang.NoClassDefFoundError: okhttp3/internal/http2/ConnectionShutdownException
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:131)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.binance.api.client.security.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:56)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall.execute(RealCall.java:69)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:52)
        at com.binance.api.client.impl.BinanceApiRestClientImpl.getPrice(BinanceApiRestClientImpl.java:116)
        at com.gamechanger.binance.production.App.lambda$0(App.java:77)
        at com.binance.api.client.impl.BinanceApiWebSocketListener.onMessage(BinanceApiWebSocketListener.java:45)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: okhttp3.internal.http2.ConnectionShutdownException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 23 more

**Comment by big-andy-coates** [comment]
The `java.lang.NoClassDefFoundError` is strange. This generally suggests a missing or wrong dependency on the class path.

I might be useful to leave the application running in the debugger with a breakpoint in the `NoClassDefFoundError` constructors so that you can work out _what_ class is not found.

**Comment by mironbalcerzak** [comment]
`mvn dependency:tree` to the rescue. Scan your project and check whether you are not having different (or out-dated) version of okhttp.

**Comment by joaopsilva** [comment]
Closing as this has to do with another dependency of the project.
