### ISSUE TITLE
Issue when call getMyTrades()

### ISSUE THREAD

**Issue by truonghatsts** [binance-exchange/binance-java-api#157]
When I call this BinanceApiRestClientImpl.getMyTrades(), it thrown below exception:

```
com.binance.api.client.exception.BinanceApiException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "symbol" (class com.binance.api.client.domain.account.Trade), not marked as ignorable (11 known properties: "commissionAsset", "qty", "isBestMatch", "price", "isMaker", "commission", "time", "tradeId", "orderId", "id", "isBuyer"])
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 13] (through reference chain: java.util.ArrayList[0]->com.binance.api.client.domain.account.Trade["symbol"])
        at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:60)
        at com.binance.api.client.impl.BinanceApiRestClientImpl.getMyTrades(BinanceApiRestClientImpl.java:183)
        at com.binance.api.client.impl.BinanceApiRestClientImpl.getMyTrades(BinanceApiRestClientImpl.java:193)
```

@joaopsilva : I believe it's because of the new api change.

**Comment by mreanaa** [comment]
I get same error

**Comment by pahgo** [comment]
The issue seems to be when there is content in the response as it contains a field called [symbol ](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#account-trade-list-user_data) that the Trade object doesn't have. I created the PR #159

**Comment by sharatsahni1** [comment]
I get the same error .. any timelines as to when would this be resolved ?

**Comment by joaopsilva** [comment]
It's fixed now, thanks for the contrib @pahgo .

**Comment by joaopsilva** [comment]
@sharatsahni1 please update the repo.

**Comment by sharatsahni1** [comment]
It was some configuration issue at my end. Its working fine now - Thanks
