### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: okio.ByteString.startsWith(Lokio/ByteString;)Z

### ISSUE THREAD

**Issue by yogi-dmt** [binance-exchange/binance-java-api#164]
```
Exception in thread "main" java.lang.NoSuchMethodError: okio.ByteString.startsWith(Lokio/ByteString;)Z
	at okhttp3.internal.http2.Hpack$Writer.writeHeaders(Hpack.java:516)
	at okhttp3.internal.http2.Http2Writer.headers(Http2Writer.java:299)
	at okhttp3.internal.http2.Http2Writer.synStream(Http2Writer.java:127)
	at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:250)
	at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:222)
	at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:111)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:50)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.binance.api.client.security.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:52)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getOpenOrders(BinanceApiRestClientImpl.java:161)
	at Trader.Trader.clearOpenOrders(Trader.java:218)
	at Trader.Trader.run(Trader.java:252)
	at Trader.Trader.main(Trader.java:278)
```

I've tried reinstalling the project into my maven, emptying out my entire repo, updating all my snapshots, cleaning the project, etc. any idea why i'm getting this error?

**Comment by swapnil-pandey** [comment]
@yogi-dmt DId you figure out the cause of this error? I am getting the same exception.

**Comment by Emperorlou** [comment]
I'm also getting this error. @swapnil-pandey Did YOU figure it out? lol
