### ISSUE TITLE
Cannot get ExchangeInfo

### ISSUE THREAD

**Issue by truonghatsts** [binance-exchange/binance-java-api#169]
I saw this error when trying to get the exchangeInfo, please help to check.

```
com.binance.api.client.exception.BinanceApiException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.binance.api.client.domain.general.RateLimitType` from String "REQUEST_WEIGHT": value not one of declared Enum instance names: [REQUESTS, ORDERS]
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 77] (through reference chain: com.binance.api.client.domain.general.ExchangeInfo["rateLimits"]->java.util.ArrayList[0]->com.binance.api.client.domain.general.RateLimit["rateLimitType"])
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:60)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getExchangeInfo(BinanceApiRestClientImpl.java:59)
```

**Comment by truonghatsts** [comment]
Close this ticket i used the old version of library.
