### ISSUE TITLE
BinanceApiException

### ISSUE THREAD

**Issue by Maldoxxx** [binance-exchange/binance-java-api#17]
Hi,
thank you very much for sharing this good and usefull code.

I'have just started with java some months ago and i'm trying run some of the examples, everything goes well except for the classes where apikey and secret is needed. I'm filling the arguments apikey and secret with my numbers and after running I get this error:

Exception in thread "main" com.binance.api.client.exception.BinanceApiException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "updateTime" (class com.binance.api.client.domain.account.Account), not marked as ignorable (8 known properties: "canTrade", "takerCommission", "balances", "sellerCommission", "buyerCommission", "makerCommission", "canWithdraw", "canDeposit"])
 at [Source: okhttp3.ResponseBody$BomAwareReader@a9cd3b1; line: 1, column: 164] (through reference chain: com.binance.api.client.domain.account.Account["updateTime"])
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:60)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getAccount(BinanceApiRestClientImpl.java:139)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getAccount(BinanceApiRestClientImpl.java:144)
	at com.binance.api.examples.AccountBalanceCacheExample.main(AccountBalanceCacheExample.java:84)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "updateTime" (class com.binance.api.client.domain.account.Account), not marked as ignorable (8 known properties: "canTrade", "takerCommission", "balances", "sellerCommission", "buyerCommission", "makerCommission", "canWithdraw", "canDeposit"])
 at [Source: okhttp3.ResponseBody$BomAwareReader@a9cd3b1; line: 1, column: 164] (through reference chain: com.binance.api.client.domain.account.Account["updateTime"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:855)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1083)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1389)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1367)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:266)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1575)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1183)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:52)
	... 3 more

Can you help me to find the reason? 

Thank you!

**Comment by joaopsilva** [comment]
Hi @Maldoxxx ,  could you please update your repository? That issue was fixed a few weeks ago. Thanks.

**Comment by lonewolf-github** [comment]
Still have the same issue
