### ISSUE TITLE
NPE when calling NewOrderResponse.toString().

### ISSUE THREAD

**Issue by big-andy-coates** [binance-exchange/binance-java-api#173]
I'm seeing an NPE thrown with the latest version when I call `toString` on the `NewOrderResponse` returned by the API.  Looking into the reason, it is because the `fills` field is `null` and `toString` is not handling this.  I've checked the response from the server and it doesn't include a `fills` field. (The order was successful).

```
Caused by: java.lang.NullPointerException
	at com.binance.api.client.domain.account.NewOrderResponse.toString(NewOrderResponse.java:179)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at org.github.datalorax.cointrader.binance.BinanceClient$BinanceMarket.placeOrder(BinanceClient.java:371)
	... 14 more
```

**Comment by joaopsilva** [comment]
This is now fixed.
