### ISSUE TITLE
Jackson Parsing Exception on call to BinanceApiRestClient.getExchangeInfo()

### ISSUE THREAD

**Issue by Etherous** [binance-exchange/binance-java-api#176]
It looks like Jackson is failing to response JSON from getExchangeInfo because it doesn't recognize the 'REQUEST_WEIGHT' limit enum value

`
 net.sealake.binance.api.client.exception.BinanceApiException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of net.sealake.binance.api.client.domain.general.RateLimitType from String value ("REQUEST_WEIGHT"): value not one of declared Enum instance names: [REQUESTS, ORDERS]
 at [Source: okhttp3.ResponseBody$BomAwareReader@68034211; line: 1, column: 77] (through reference chain: net.sealake.binance.api.client.domain.general.ExchangeInfo["rateLimits"]->java.util.ArrayList[0]->net.sealake.binance.api.client.domain.general.RateLimit["rateLimitType"])
	at net.sealake.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:62) ~[binance-api-client-1.0.0.RELEASE.jar:?]
	at net.sealake.binance.api.client.impl.BinanceApiRestClientImpl.getExchangeInfo(BinanceApiRestClientImpl.java:59) ~[binance-api-client-1.0.0.RELEASE.jar:?]
	...
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of net.sealake.binance.api.client.domain.general.RateLimitType from String value ("REQUEST_WEIGHT"): value not one of declared Enum instance names: [REQUESTS, ORDERS]
 at [Source: okhttp3.ResponseBody$BomAwareReader@68034211; line: 1, column: 77] (through reference chain: net.sealake.binance.api.client.domain.general.ExchangeInfo["rateLimits"]->java.util.ArrayList[0]->net.sealake.binance.api.client.domain.general.RateLimit["rateLimitType"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:923) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:135) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:86) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1575) ~[jackson-databind-2.7.2.jar:2.7.2]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1183) ~[jackson-databind-2.7.2.jar:2.7.2]
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32) ~[converter-jackson-2.3.0.jar:?]
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23) ~[converter-jackson-2.3.0.jar:?]
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119) ~[retrofit-2.3.0.jar:?]
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218) ~[retrofit-2.3.0.jar:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) ~[retrofit-2.3.0.jar:?]
	at net.sealake.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:54) ~[binance-api-client-1.0.0.RELEASE.jar:?]
	... 21 more
`

**Comment by joaopsilva** [comment]
This was recently fixed, please run `git pull` to update your project with the latest version.
