### ISSUE TITLE
Market data query timeout.

### ISSUE THREAD

**Issue by GazitGu** [binance-exchange/binance-java-api#184]
Hi, I downloaded the code today, and when i run the market data query (run MarketDataEndpointsExample without any change), i got a read time out issue, but i can open Binance website and see the market data change, is any thing wrong?

Below is the exception:
Exception in thread "main" com.binance.api.client.exception.BinanceApiException: java.net.SocketTimeoutException: connect timed out
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:71)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getOrderBook(BinanceApiRestClientImpl.java:72)
	at com.binance.api.examples.MarketDataEndpointsExample.main(MarketDataEndpointsExample.java:26)

Thanks,

GC

**Comment by joaopsilva** [comment]
Not really sure, I'm unable to reproduce the problem with the latest version. Perhaps your firewall is blocking the connection?
