### ISSUE TITLE
getCandlestickBars API fails with exception

### ISSUE THREAD

**Issue by nawab36085** [binance-exchange/binance-java-api#199]
Getting exception while using getCandlestickBars API. I am using it in an Android project using Android Studio. Tried updating all the jackson components as well as corresponding jar files. But the problem persists.

Here is the exception:

Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String "3449.47000000": not a valid Long value
        at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 17] (through reference chain: java.util.ArrayList[0]->com.binance.api.client.domain.market.Candlestick["closeTime"])
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1549)
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:911)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer._parseLong(NumberDeserializers.java:584)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:557)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:535)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.impl.BeanAsArrayDeserializer.deserialize(BeanAsArrayDeserializer.java:119)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:92)
        at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:72)
        at com.binance.api.client.impl.BinanceApiRestClientImpl.getCandlestickBars(BinanceApiRestClientImpl.java:97) 
        at com.binance.api.client.impl.BinanceApiRestClientImpl.getCandlestickBars(BinanceApiRestClientImpl.java:102) 
        at com.spotthelost.myapplication.SymbolsActivity$UserLoginTask.doInBackground(SymbolsActivity.java:234) 
        at com.spotthelost.myapplication.SymbolsActivity$UserLoginTask.doInBackground(SymbolsActivity.java:206) 
        at android.os.AsyncTask$2.call(AsyncTask.java:304) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:762)

**Comment by volsahin** [comment]
Same here

**Comment by nawab36085** [comment]
I have solved this issue. However, I dont have a permission to create a branch in this repo, therefore I cant create a pull request. If @joaopsilva you could provide me permission, I would push the changes and create a pull request.

**Comment by joaopsilva** [comment]
Are you using the latest version? I can't reproduce the problem locally.

**Comment by javimagro** [comment]
I have the same problem.  I am using gradle with :      implementation 'com.github.binance-exchange:binance-java-api:master-SNAPSHOT'

When I call to :                 CS = client.getCandlestickBars( Coin, CandlestickInterval.DAILY ) ;

I get the Java exception : 


Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String "0.00003093": not a valid Long value

**Comment by JitanderVerma** [comment]
> I have solved this issue. However, I dont have a permission to create a branch in this repo, therefore I cant create a pull request. If @joaopsilva you could provide me permission, I would push the changes and create a pull request.

How?.. Can you help me in this thing?
