### ISSUE TITLE
Error : "Trust anchor for certification path not found."

### ISSUE THREAD

**Issue by VaultDeveloper** [binance-exchange/binance-java-api#20]
Hello,

I have try on several Android devices and it seems I have the same problem. I got the exception "Trust anchor for certification path not found".

>Stacktrace : com.binance.api.client.exception.BinanceApiException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                  at com.binance.api.client.impl.BinanceApiCallbackAdapter.onFailure(BinanceApiCallbackAdapter.java:45)
                                                                                  at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$2.run(ExecutorCallAdapterFactory.java:79)
                                                                                  at android.os.Handler.handleCallback(Handler.java:808)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                  at android.os.Looper.loop(Looper.java:193)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                                                                                  at dalvik.system.NativeStart.main(Native Method)
                                                                               Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                  at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410)
                                                                                  at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
                                                                                  at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
                                                                                  at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
                                                                                  at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
                                                                                  at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
                                                                                  at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
                                                                                  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                  at com.binance.api.client.security.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:55)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                                  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                                  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                  at java.lang.Thread.run(Thread.java:848)
                                                                               Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                  at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282)
                                                                                  at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)
                                                                                  at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:612)
                                                                                  at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                                  at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
                                                                                  at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281) 
                                                                                  at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251) 
                                                                                  at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151) 
                                                                                  at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192) 
                                                                                  at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121) 
                                                                                  at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100) 
                                                                                  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                                  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                                  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                                  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) 
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                                  at com.binance.api.client.security.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:55) 
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                                  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) 
                                                                                  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135) 
                                                                                  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                  at java.lang.Thread.run(Thread.java:848) 
                                                                               Caused by: java.security.cert.CertPathValidatorException: Trust anchor for

My code :
`BinanceApiClientFactory factory = BinanceApiClientFactory.newInstance(APIKEY_, APISECRET_);
        BinanceApiAsyncRestClient binance = factory.newAsyncRestClient();
        binance.ping((BinanceApiCallback) -> {
            Show(BinanceApiCallback.toString());
        });`

Same problem with the not Async client.

The same problem was found here : https://github.com/ccxt/ccxt/issues/882
And seems to be revolved here : https://github.com/ccxt/ccxt/issues/882#event-1397310119

I also found this problem in common issues : https://developer.android.com/training/articles/security-ssl.html#CommonProblems

Hope I can be fixed easily and fastly 🥇 

PS : This error was in the master : https://github.com/joaopsilva/binance-java-api/issues/3

**Comment by harrison-n** [comment]
I'm having the same issue.

**Comment by flyman3046** [comment]
Same issue here.

**Comment by joaopsilva** [comment]
Hi guys, can any of you create a PR for this? I can't reproduce it at the moment with my devices.

**Comment by big-andy-coates** [comment]
It looks to me like you're running your applications with a custom truststore, and that truststore does not trust the Binance SSL cert or CA.
