### ISSUE TITLE
Filter failure: PERCENT_PRICE

### ISSUE THREAD

**Issue by w343972820** [binance-exchange/binance-java-api#200]
Exception in thread "main" com.binance.api.client.exception.BinanceApiException: Filter failure: PERCENT_PRICE
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:57)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.newOrder(BinanceApiRestClientImpl.java:97)

**Comment by joaopsilva** [comment]
Please refer to https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#percent_price.
