### ISSUE TITLE
getExchangeInfo

### ISSUE THREAD

**Issue by zhangxd1222** [binance-exchange/binance-java-api#231]
Can not construct instance of com.binance.api.client.domain.general.RateLimitType from String value ("REQUEST_WEIGHT"): value not one of declared Enum instance names: [REQUESTS, ORDERS]
 at [Source: okhttp3.ResponseBody$BomAwareReader@4b79ac84; line: 1, column: 77] (through reference chain: com.binance.api.client.domain.general.ExchangeInfo["rateLimits"]->java.util.ArrayList[0]->com.binance.api.client.domain.general.RateLimit["rateLimitType"])

**Comment by jbaron** [comment]
Here also facing same issue. A  slightly larger stack-trace:

```
com.binance.api.client.exception.BinanceApiException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.binance.api.client.domain.general.RateLimitType` from String "RAW_REQUESTS": not one of the values accepted for Enum class: [REQUEST_WEIGHT, ORDERS]
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 311] (through reference chain: com.binance.api.client.domain.general.ExchangeInfo["rateLimits"]->java.util.ArrayList[3]->com.binance.api.client.domain.general.RateLimit["rateLimitType"])

	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:79)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getExchangeInfo(BinanceApiRestClientImpl.java:43)
	at org.roboquant.binance.BinanceConnection.retrieveAssets(BinanceConnection.kt:23)
	at org.roboquant.binance.BinanceHistoricFeed$availableAssets$2.invoke(BinanceHistoricFeed.kt:31)
	at org.roboquant.binance.BinanceHistoricFeed$availableAssets$2.invoke(BinanceHistoricFeed.kt:30)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
```

The code I execute is just to get the available symbols via the getExchangeInfo on a standard RestClient

**Comment by thedarthonian** [comment]
Hitting the same issue, any update on this?
