### ISSUE TITLE
java.net.SocketTimeoutException on onAllMarketTickersEvent

### ISSUE THREAD

**Issue by VLEFF** [binance-exchange/binance-java-api#282]
Hello, I keep getting this unfamous error after subscribing to onAllMarketTickersEvent() socket, after like 30-40s

java.net.SocketTimeoutException: sent ping but didn't receive pong within 20000ms (after 1 successful ping/pongs)
	at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:545)
	at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:529)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

What is strange is that I subscribe to the depth socket in the same time, and this one works like a charm.
Am I the only one that keep getting this error?

**Comment by ntaouros** [comment]
I am also getting this from time to time. any updates?
