### ISSUE TITLE
'recvWindow' must be less than 60000.

### ISSUE THREAD

**Issue by AlexanderTrybushnyi** [binance-exchange/binance-java-api#313]
Exception in thread "main" com.binance.api.client.exception.BinanceApiException: 'recvWindow' must be less than 60000.
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:57)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getAccount(BinanceApiRestClientImpl.java:139)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getAccount(BinanceApiRestClientImpl.java:144)
	at com.binance.api.examples.AccountBalanceCacheExample.initializeAssetBalanceCacheAndStreamSession(AccountBalanceCacheExample.java:44)
	at com.binance.api.examples.AccountBalanceCacheExample.<init>(AccountBalanceCacheExample.java:33)
	at com.binance.api.examples.AccountBalanceCacheExample.main(AccountBalanceCacheExample.java:79)

**Comment by aosynsky** [comment]
that's because in NewOrder constructor recvWindow harcoded to 6000000L...
As workaround, You can override value by calling "recvWindow" method and setting correct value.

**Comment by AlexanderTrybushnyi** [comment]
> that's because in NewOrder constructor recvWindow harcoded to 6000000L...
> As workaround, You can override value by calling "recvWindow" method and setting correct value.

Hey! But what is the correct value? 5000000L?

**Comment by AlexanderTrybushnyi** [comment]
> that's because in NewOrder constructor recvWindow harcoded to 6000000L...
> As workaround, You can override value by calling "recvWindow" method and setting correct value.

Do you have stable version?
