### ISSUE TITLE
StackOverflowError with the AuthenticationInterceptor after several hours of swing trading

### ISSUE THREAD

**Issue by gizmochief7** [binance-exchange/binance-java-api#54]
Twice now I have received this StackOverflowError while doing normal trading. The Project is set up with a key and secret in live trading environment. Each time I was running a swing trading strategy on ONE_MINUTE intervals. It was executing a Buy when the error occurred. The first time it failed was after running for 128 minutes and the second time was after 162 minutes. Each of those windows contained numerous successful buy and sell trades. This was not caught and the whole program crashed. Any thoughts as to a patch the error so that the program will recover? You will notice the infinite loop being called into the following file. I have provide the full stacktrace of the StackOverflowError cutting off the part after where the pattern is oviously repeating. You will also notice the okhttp3 lib actually starts to repeat before the interceptor starts to loop with it. 

https://github.com/binance-exchange/binance-java-api/blob/382a679ac0e0d31bc002e4d2927e8afad283f12e/src/main/java/com/binance/api/client/security/AuthenticationInterceptor.java#L55

Full Stacktrace:
```
Exception in thread "OkHttp Dispatcher" java.lang.StackOverflowError
	at java.lang.System.getProperty(System.java:714)
	at sun.security.action.GetPropertyAction.run(GetPropertyAction.java:84)
	at sun.security.action.GetPropertyAction.run(GetPropertyAction.java:49)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Debug.getBooleanProperty(Debug.java:184)
	at sun.security.ssl.SSLSessionImpl.<init>(SSLSessionImpl.java:767)
	at sun.security.ssl.ClientHandshaker.serverHello(ClientHandshaker.java:664)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:206)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.binance.api.client.security.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:55)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.binance.api.client.security.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:55)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.binance.api.client.security.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:55)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.binance.api.client.security.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:55)
        .
        .
        .
```
Start of the repeating pattern: 
```
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.binance.api.client.security.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:55)
```

**Comment by Willthegod** [comment]
I had the same issue...

**Comment by Micha1990** [comment]
Same issue here..

**Comment by joaopsilva** [comment]
@gizmochief7 this happened when placing a new order?

**Comment by gizmochief7** [comment]
@joaopsilva Yes, but not every time I placed a new order. It would happen after several hours of successful buying and selling transactions. I added in a temp hack that sorta helped by clearing the interceptors list when `createService` method was called in the `BinanceApiServiceGenerator` class. The reason I did this hack (and by no means am I saying this was the fix), I found in a `okhttp3` form that it was suggested to clear the list. I also added some debugging to the interceptor that just counted how many times it was called. I found that every interceptor that was in the list was called ever time a new interceptor was added which grew at a factorial rate which eventually lead to the `stackoverFlow`. The error went away but it would then just stop receiving web socket events a few hours later as @lange88 commented on @datalorax PR 3 days ago ["after ~16 hours of streaming the web sockets are no longer receiving any data (no exceptions are thrown, the data just stops)"](https://github.com/binance-exchange/binance-java-api/pull/49) I decided to just stop using it until the web socket connection was stable. So I've been checking in every couple days to see if you had merged @datalorax pull request [Error handling and shutdown improvements](https://github.com/binance-exchange/binance-java-api/pull/49). I'm hoping these fixes make it stable. However, I did a quick test using his and where i expected to receive an error to happen so that i could clean up the connection, close the socket and reopen it but I found that it didn't throw an error and quietly wasn't working. Hopefully when @datalorax pull request is merged, this will fix the issues. As a side note, I would love to see an example of setting up the websocket with restart fail-over in place so has been shown to last a couple days. The same would be nice for User data stream. I see the same problem the @octn brought up in [User data stream premature closing](https://github.com/binance-exchange/binance-java-api/issues/4)

**Comment by datalorax** [comment]
I've raised the above PR to fix this issue.

Note: while the above PR fixes this issue, the fact you are seeing this issue suggests that your application is frequently creating new Binance clients, (rest or ws), rather than creating a client once and re-using.  You should probably also look to create the client once!

**Comment by joaopsilva** [comment]
Indeed @gizmochief7 , you should re-use the client.
