### ISSUE TITLE
PKIX path building failed

### ISSUE THREAD

**Issue by zagorulkinde** [binance-exchange/binance-java-api#64]
Hello. I'm trying to listen websocket notifications from binance by this simple code:

```
public class WebSocketReader implements Runnable {
    private final String[] tickers;
    private final BinanceApiWebSocketClient client = BinanceApiClientFactory
            .newInstance().newWebSocketClient();

    private BlockingQueue<DepthEvent> queue;

    public WebSocketReader(String[] tickers, BlockingQueue<DepthEvent> queue) {
        this.tickers = tickers;
        this.queue = queue;
    }

    @Override
    public void run() {
        Arrays.stream(tickers).forEach(t -> client.onDepthEvent(t,
                response -> {
                    queue.add(response);
                }));
    }
}

```
```
ExecutorService executor = Executors.newCachedThreadPool();
BlockingQueue<DepthEvent> queue = new ArrayBlockingQueue<DepthEvent>(10000, true);
executor.submit(new WebSocketReader(new String[]{"ethbtc"}, queue));
```

and this code throws exception on my mac and works nice on linux:

> Exception in thread "OkHttp Dispatcher" com.binance.api.client.exception.BinanceApiException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at com.binance.api.client.impl.BinanceApiWebSocketListener.onFailure(BinanceApiWebSocketListener.java:51)
> 	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:543)
> 	at okhttp3.internal.ws.RealWebSocket$2.onFailure(RealWebSocket.java:208)
> 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:148)
> 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
> 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1917)
> 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:301)
> 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:295)
> 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1471)
> 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
> 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:936)
> 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:871)
> 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)
> 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
> 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
> 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
> 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
> 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
> 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
> 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
> 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
> 	... 4 more
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
> 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
> 	at sun.security.validator.Validator.validate(Validator.java:260)
> 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
> 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
> 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
> 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1453)
> 	... 30 more
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
> 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
> 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
> 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
> 	... 36 more
>

**Comment by zagorulkinde** [comment]
Actually i know that it's possible to download certificate by hand to save it jks but it sounds strange because on linux it works fine.

**Comment by deuteragenie** [comment]
As this API is supposed to access only the Binance servers, why not implement X509TrustManager to remove the cumbersome certificate import process ?

**Comment by joaopsilva** [comment]
@deuteragenie that would pose a security problem if the servers were to be compromised.

**Comment by deuteragenie** [comment]
@joaopsilva If the server certificates were to be compromised, the Binance server certificate would change... obviously. Another potential issue is a man in the middle attack though.

What I would think of is to implement a X509TrustManager that unpack the received X509Certificate and a) compares the IP address and/or domain name of the server being accessed with the expected one and b) compares the expected X509Certificate signature value with the received one.

Shouldn't this be be safe ? Unless someone compromises this repository, or the .jar file, etc. but that is very much the case also if someone compromises the trusted store.
