### ISSUE TITLE
getExchangeInfo causes GenericSignatureFormatError

### ISSUE THREAD

**Issue by deuteragenie** [binance-exchange/binance-java-api#69]
`Exception in thread "main" java.lang.reflect.GenericSignatureFormatError: Signature Parse error: Expected Field Type Signature
	Remaining input: +Lcom/binance/api/client/exception/BinanceApiException;
	at sun.reflect.generics.parser.SignatureParser.error(SignatureParser.java:124)
	at sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:297)
	at sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:283)
	at sun.reflect.generics.parser.SignatureParser.parseTypeSignature(SignatureParser.java:485)
	at sun.reflect.generics.parser.SignatureParser.parseReturnType(SignatureParser.java:627)
	at sun.reflect.generics.parser.SignatureParser.parseMethodTypeSignature(SignatureParser.java:577)
	at sun.reflect.generics.parser.SignatureParser.parseMethodSig(SignatureParser.java:171)
	at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:55)
	at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:43)
	at sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
	at sun.reflect.generics.repository.GenericDeclRepository.<init>(GenericDeclRepository.java:48)
	at sun.reflect.generics.repository.ConstructorRepository.<init>(ConstructorRepository.java:51)
	at sun.reflect.generics.repository.MethodRepository.<init>(MethodRepository.java:46)
	at sun.reflect.generics.repository.MethodRepository.make(MethodRepository.java:59)
	at java.lang.reflect.Method.getGenericInfo(Method.java:102)
	at java.lang.reflect.Method.getGenericInfo(Method.java:61)
	at java.lang.reflect.Executable.getGenericParameterTypes(Executable.java:284)
	at java.lang.reflect.Method.getGenericParameterTypes(Method.java:282)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.getParameterType(AnnotatedMethod.java:145)
	at com.fasterxml.jackson.databind.introspect.AnnotatedWithParams.getParameter(AnnotatedWithParams.java:86)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreators(POJOPropertiesCollector.java:473)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:313)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:287)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:170)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:346)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:330)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:255)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:214)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:137)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:1938)
	at com.fasterxml.jackson.databind.ObjectReader.<init>(ObjectReader.java:189)
	at com.fasterxml.jackson.databind.ObjectMapper._newReader(ObjectMapper.java:658)
	at com.fasterxml.jackson.databind.ObjectMapper.readerFor(ObjectMapper.java:3506)
	at retrofit2.converter.jackson.JacksonConverterFactory.responseBodyConverter(JacksonConverterFactory.java:60)
	at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
	at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
	at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:736)
	at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:169)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
	at com.sun.proxy.$Proxy0.getExchangeInfo(Unknown Source)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getExchangeInfo(BinanceApiRestClientImpl.java:56)`

**Comment by joaopsilva** [comment]
Hi @deuteragenie , I'm unable to reproduce this problem. My guess is that you are passing a wrong API-KEY to the client.
