### ISSUE TITLE
JsonParseException in BinanceApiRestClientImpl#getAggTrades

### ISSUE THREAD

**Issue by brintal** [binance-exchange/binance-java-api#84]
From time to time, I'm getting the following error when calling getAggTrades in BinanceApiRestClientImpl:

`com.binance.api.client.exception.BinanceApiException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: okhttp3.ResponseBody$BomAwareReader@369d979a; line: 1, column: 2]
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:60) ~[binance-api-client-1.0.0.jar!/:na]
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getAggTrades(BinanceApiRestClientImpl.java:68) ~[binance-api-client-1.0.0.jar!/:na]
	at at.fishbot.binance.BinanceClient.getAggTrades(BinanceClient.java:230) ~[classes!/:0.0.1-SNAPSHOT]
	at at.fishbot.binance.strategy.impl.MMMJStrategy.updateEmas(MMMJStrategy.java:373) ~[classes!/:0.0.1-SNAPSHOT]
	at at.fishbot.binance.strategy.impl.MMMJStrategy.execute(MMMJStrategy.java:78) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: okhttp3.ResponseBody$BomAwareReader@369d979a; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[jackson-core-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1906) ~[jackson-core-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749) ~[jackson-core-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:355) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32) ~[converter-jackson-2.3.0.jar!/:na]
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23) ~[converter-jackson-2.3.0.jar!/:na]
	at com.binance.api.client.impl.BinanceApiServiceGenerator.getBinanceApiError(BinanceApiServiceGenerator.java:69) ~[binance-api-client-1.0.0.jar!/:na]
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:56) ~[binance-api-client-1.0.0.jar!/:na]
	... 12 common frames omitted`

**Comment by joaopsilva** [comment]
This seems like a connection issue, where the endpoint is overloaded (on the Binance side), or does not respond. The best course of action would be to handle the exception and try again.

**Comment by 22prueba22** [comment]
Please open again:

Hello git,

We are also having this strange error on the GetOrderStatus. We think maybe the exchangerId of an order has this character, and jackson is not scaping them?

`com.binance.api.client.exception.BinanceApiException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' o
r 'null')
 at [Source: okhttp3.ResponseBody$BomAwareReader@2b8bfc5a; line: 1, column: 2]
        at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:60) ~[binance-java-api-master-6f53a881fc-1.jar!/:na]
        at com.binance.api.client.impl.BinanceApiRestClientImpl.getOrderStatus(BinanceApiRestClientImpl.java:140) ~[binance-java-api-master-6f53a881fc-1.jar!/:na]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: okhttp3.ResponseBody$BomAwareReader@2b8bfc5a; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.10.jar!/:2.8.10]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.10.jar!/:2.8.10]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[jackson-core-2.8.10.jar!/:2.8.10]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1906) ~[jackson-core-2.8.10.jar!/:2.8.10]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749) ~[jackson-core-2.8.10.jar!/:2.8.10]
        at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:355) ~[jackson-databind-2.8.10.jar!/:2.8.10]
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611) ~[jackson-databind-2.8.10.jar!/:2.8.10]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203) ~[jackson-databind-2.8.10.jar!/:2.8.10]
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32) ~[converter-jackson-2.3.0.jar!/:na]
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23) ~[converter-jackson-2.3.0.jar!/:na]
        at com.binance.api.client.impl.BinanceApiServiceGenerator.getBinanceApiError(BinanceApiServiceGenerator.java:69) ~[binance-java-api-master-6f53a881fc-1.jar!/:na]
        at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:56) ~[binance-java-api-master-6f53a881fc-1.jar!/:na]
        ... 11 common frames omitted
`

**Comment by tomastoth** [comment]
Getting the same error last 2 days. Trying to grab orders status. Keeps happening for like an hour and then stops. Like twice a day.
