### ISSUE TITLE
java.net.SocketTimeoutException when calling getMyTrades

### ISSUE THREAD

**Issue by brintal** [binance-exchange/binance-java-api#95]
Since a few days around 10% of my calls to BinanceApiRestClientImpl#getMyTrades run into a java.net.SocketTimeoutException:
`
com.binance.api.client.exception.BinanceApiException: java.net.SocketTimeoutException: timeout
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:60)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getMyTrades(BinanceApiRestClientImpl.java:155)`

Is anyone else experiencing this? My server is located in Hong Kong and latency to the binance servers seems to be pretty good in general. 
Maybe this call takes a long time for the binance servers to process? Can I manually increase the timeout limit somehow?

**Comment by joaopsilva** [comment]
Without seeing your exact request, it's difficult to tell where the problem is. In any case, it's most likely on the server end (and not on the api/client side).

If you want to increase the timeout, you can, by changing the configuration of the `OkHttpClient`

```
https://github.com/binance-exchange/binance-java-api/blob/master/src/main/java/com/binance/api/client/impl/BinanceApiServiceGenerator.java#L22
```
And adding `httpClient.setConnectTimeout(60, TimeUnit.SECONDS)` . However, since this is internal API code, it might break in a future release.

**Comment by brintal** [comment]
After review, the root cause seems to be:
`Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 43 common frames omitted
`
Can it be possible that this exception happens when I'm using one instance of BinanceApiRestClientImpl concurrently from multiple threads? How thread safe is BinanceApiRestClientImpl?
